services:
  scheduler:
    build: .
    volumes:
      - .:/app
    command: >
       python main.py
    networks:
      - observer_network
    restart: always
    



networks:
  observer_network:
    external: true
    name: ${OBSERVER_NETWORK}
