name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Deploy to Production
        if: github.ref_name == 'main'
        run: |
          ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          for service in observe-scheduler-1 observe-scheduler-2; do
            cd ~/apps/$service
            git pull origin main
            docker compose down
            docker compose up --build -d
          done
          EOF
